name: CD

on:
  push:
    branches: [ "cd/*" , "cd/*/*" ]

  workflow_dispatch:

jobs:

  call-merge-workflow:
    uses: ./.github/workflows/merge.yaml

  call-deploy-workflow:
    uses: mrog9/zeptoGroceries_aws/.github/workflows/deploy.yaml@main

