name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "ci/*" , "ci/*/*" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:

  call-test-workflow:
    uses: ./.github/workflows/test.yaml

  call-build-workflow:
    needs: call-test-workflow
    uses: ./.github/workflows/build.yaml

  call-merge-workflow:
    needs: call-build-workflow
    uses: ./.github/workflows/merge.yaml

  call-deploy-workflow:
    needs: call-merge-workflow
    uses: mrog9/zeptoGroceries_aws/.github/workflows/deploy.yaml@main